### ISSUE TITLE
[FR] Any chance to get this included as a nand patch in I.e Jrunner

### ISSUE THREAD

**Issue by aenertia** [InvoxiPlayGames/UsbdSecPatch#1]
Would be nice to have this included in nand dash build.

**Comment by Sk1ller1993** [comment]
There you go! https://github.com/Sk1ller1993/J-Runner-with-Extras

**Comment by baabo** [comment]
This patch is now included in the J-Runner with Extras by Octal450.
At least for me, the XeBuild patch works better than the Dashlaunch patch. With the XeBuild patch, I don't have to replug the controller (mayflash adapter) when the console boots.

**Comment by iMrDJAi** [comment]
@Sk1ller1993 Can you please tell me how did you achieve this setup?

![image](https://github.com/InvoxiPlayGames/UsbdSecPatch/assets/42304709/e8dbc87e-3a69-436e-8df1-64c893046e24)

**Comment by InvoxiPlayGames** [comment]
Closing this issue, J-Runner with Extras has included this for over a year (as of V3.2.2-r2). https://github.com/Octal450/J-Runner-with-Extras
