### ISSUE TITLE
Any guide to use it?

### ISSUE THREAD

**Issue by XxyZwW** [InvoxiPlayGames/UsbdSecPatch#8]
I tried installing it on the console and activating it at startup with Dashlaunch, I have a Wii guitar connected through a Raspberry pi pico adapter with Santroller, I tried leaving the guitar connected and turning on the Xbox, entering RB3 and it doesn't pull, I tried again connecting the guitar after the Xbox 360 splash logo, I started RB3 and it also, nothing, does not detect the guitar.
Do you know if running the patch from Dashlaunch is the correct way or if I have to embed it into the NAND? Is there any specific configuration that I have to configure in Santroller?

There is very little information on the internet on how to use it.

**Comment by InvoxiPlayGames** [comment]
In Santroller you'll want to make sure "Passthrough auth for Xbox 360 controllers" is **disabled** if you have a USB host port set up. Make sure you're using the latest version of Santroller as well.

**Comment by h3llb3nt** [comment]
https://consolemods.org/wiki/Xbox_360:Using_Modern_Controllers

**Comment by XxyZwW** [comment]
Thank you so much, I tried and works, the key tip was: make sure "Passthrough auth for Xbox 360 controllers" is disabled thank you
